services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      CLIENT_ENCODING: UTF8
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data


  room_booking:
    build:
      dockerfile: ./apps/room_booking/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
    depends_on:
      - database

volumes:
  data: